name: Publish Docker image

on:
    push:
        branches: 
            - main


jobs: 
    build:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up jdk
              uses: actions/setup-java@v4
              with:
                java-version: '22'
                distribution: 'temurin'

            - name: build docker image
              run: docker build -t hello-docker .

            - name: Login to Dockerhub
              run: echo "${{ secrets.DH_PW }}" | docker login -u ${{ secrets.DH_UN }} --password-stdin

# docker login         - användarnamn och lösenord till dockerhub -> secret till github Action

# docker build -t ....


# docker push