name: Publish Docker image

on:
    push:
        branches: 
            - main


jobs: 
    build:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up jdk
              uses: actions/setup-java@v4
              with:
                java-version: '22'
                distribution: 'temurin'

            - name: build docker image
              run: docker build -t helloDocker .

            - name: Login to Dockerhub
              run: echo "running"

# docker login         - användarnamn och lösenord till dockerhub -> secret till github Action

# docker build -t ....


# docker push